### ISSUE TITLE
Transtyping some Fortran Comm to python result in an OverflowError

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#293]
For example, when running the provided example with logging enabled (MPI only, rank 1 only):
```
[PDI][MPI][000001][11:13:28] *** debug: Transtype `mpi_comm_F' to `mpi_comm'
[PDI][MPI][000001][11:13:28] *** debug: Transtyped (F->C) `1140850688' to `0x7fe644000000'
[PDI][MPI][000001][11:13:28] *** debug: `mpi_comm_F' no longer available, reclaim transtyped desc (`mpi_comm')
[PDI][MPI][000001][11:13:28] *** debug: Transtype back `mpi_comm' to `mpi_comm_F'
[PDI][MPI][000001][11:13:28] *** debug: Transtyped (C->F) `0x7fe684000002' to `-2080374782'
Traceback (most recent call last):
  File "/builds/pdidev/pdi/example/example.py", line 110, in <module>
    main_comm = MPI.Comm.f2py(main_comm_f)
  File "mpi4py/MPI/Comm.pyx", line 1147, in mpi4py.MPI.Comm.f2py
OverflowError: value too large to convert to MPI_Fint
```

Here one can see that :
* 1140850688 == 0x44000000 (F) -> 0x7fe644000000
* 0x7fe684000002 (C) -> 0x84000002 == +2214592514 (`uint32_t`) == -2080374782 (`int32_t`)

This all looks pretty nice, except python decides that negative `int32_t` are not fair game...

**Comment by jbigot** [comment]
Workaround by disabling `PDI_example_fti_P`, this should be solved instead

**Comment by jbigot** [comment]
mentioned in commit fcbe13c5b6974b45230281bde41d5e7e5595ace5

**Comment by jbigot** [comment]
mentioned in commit 72df0903d0a226ca18a8c6505897c0c9f371c4dd

**Comment by jbigot** [comment]
mentioned in commit c344430a33db4a6dd548de489e642ee2a4ccc185

**Comment by jbigot** [comment]
mentioned in commit 32fd844de9f132bbe4b26cb098148adda4846648

**Comment by jbigot** [comment]
mentioned in commit d37de8f58d0b28d0cee765d2b0c165e15a12e351

**Comment by jbigot** [comment]
mentioned in commit 4fa1d01e6c444faff41425bc232016e8c2d650d4

**Comment by jbigot** [comment]
mentioned in commit b1359cc70ebe383b4c29dcdefbee88c9c597c60d

**Comment by jbigot** [comment]
mentioned in commit 52047e169514a8b44e1cc7eb0b8e9d7489e8eff1

**Comment by jbigot** [comment]
mentioned in commit 045516e37050adb700a11c7587ffd04a5488bb32

**Comment by jbigot** [comment]
mentioned in commit 8560b733dfa6efc97eb9afd051d5f6b06161c65c

**Comment by jbigot** [comment]
The issue is that in https://gitlab.maisondelasimulation.fr/pdidev/pdi/-/blob/master/plugins/mpi/mpi.cxx#L120 we cast the received type to `MPI_Fint`. This is not assured. If this is a larger type and we set a negative value, we will store a large positive value instead.

**Comment by jbigot** [comment]
mentioned in commit 9bc4a043f5ca020f37e8988b1fa1f822b640b457

**Comment by jbigot** [comment]
mentioned in commit 48080e26c39ec9090fc0e26c4dab469ba21a8c5f
